---
title: "2023: Day 5"
date: 2023-12-5
categories:
  - TAG_1
  - TAG_2
draft: false
---

## Setup

[The original challenge](https://adventofcode.com/2023/day/5)

[My data](input){target="_blank"}

## Part 1

```{r}
#| echo: false
OK <- "2023" < 3000
# Will only evaluate next code block if an actual year has been substituted for the placeholder
```


```{r}
#| eval: !expr OK
library(aochelpers)
# other options: aoc_input_data_frame(), aoc_input_matrix()
input <- aoc_input_vector(5, 2023)
head(input)
```

Partition the different maps.
```{r}
input_list <- strsplit(input, " ")
seeds <- input_list[[1]][-1]
seed2soil <- input_list[4:29]
soil2fert <- input_list[32:50]
fert2wate <- input_list[53:96]
wate2ligh <- input_list[99:119]
ligh2temp <- input_list[122:152]
temp2humi <- input_list[155:203]
huni2loca <- input_list[206:247]
```

For a given vector of thee values, add the third unit to the first two to create mapping.
```{r}
add_third <- function(vec) {
	vec <- as.numeric(vec)
	dst_val <- vec[1]:(vec[1]+vec[3])
	src_val <- vec[2]:(vec[2]+vec[3])
	data.frame(dst_val = dst_val, src_val = src_val)
}
```

Test.
```{r}
seed2soil[[1]]
head(add_third(seed2soil[[1]]))
```

Now apply this to all vectors in all lists.


## Part 2


